# application.yml
# yml - yaml - Yet Another Markup Language
# 腋毛

# 向注册中心注册时，使用这个名字作为服务id
spring:
  application:
    name: item-service
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 192.168.64.140
    port: 5672
    username: admin
    password: admin

server:
  port: 8001
  zipkin:
    sender:
      type: rabbit

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka