spring:
  application:
    name: user-service
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 192.168.64.140
    port: 5672
    username: admin
    password: admin

  zipkin:
    sender:
      type: rabbit
server:
  port: 8101

# 自定义配置属性
# 存放测试用的用户数据：[{id:7,username:张三,password:123}, {id:8,username:.....}, {id:9}]
sp:
  user-service:
    users: "[{'id':7, 'username':'张三','password':'123'},
    {'id':8, 'username':'def','password':'456'},
    {'id':9, 'username':'ghi','password':'789'},
    {'id':99, 'username':'xyz','password':'012'}]"

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka